version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile-web
    depends_on:
      - database
    networks:
      - backend
    environment:
       - ALLOW_OVERRIDE=true
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    links:
      - database
  database:
    build:
      context: .
      dockerfile: dockerfile-database
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: mysql
    ports:
      - "8889:3306"
networks:
  backend:
